### ISSUE TITLE
使用-vcodec命令报错

### ISSUE THREAD

**Issue by xjd1987** [gavinliu/FFmpegBox#1]
你好 我使用你的项目自定义的命令，为什么使用到-vcodec的时候程序会崩溃 
另外你这个项目能使用x264编码吗？

**Comment by gavinliu** [comment]
还没开发完，只是简单移植的，你可以参考这个项目。https://github.com/WritingMinds

**Comment by xjd1987** [comment]
好的  谢谢

**Comment by gavinliu** [comment]
基于 ffmpeg 二进制执行文件 + rxjava + kotlin 的版本已经更新了，支持 libx264 编码。
