### ISSUE TITLE
点击2次会报错

### ISSUE THREAD

**Issue by liuatgit** [gavinliu/FFmpegBox#2]
我遇到个bug，在你的例子里点击“裁剪GIF”按钮一次会成功，如果再点击一次“裁剪GIF”按钮则会非法操作。看来FFmpegBox只能转换一次，请问怎么修正？
谢谢！

**Comment by gavinliu** [comment]
最近工作上比较忙，没时间更新这个项目。如果你只是需要 ffmpeg 命令的话，参考我这篇博客，后续我会改成这个方式：

[Android - FFmpeg 命令行运行方式2](http://gavinliu.cn/2017/03/21/Android-FFmpeg-%E5%91%BD%E4%BB%A4%E8%A1%8C%E8%BF%90%E8%A1%8C%E6%96%B9%E5%BC%8F2/)

**Comment by liuatgit** [comment]
新建了工程测试，FFmpegBox运行第1条语句会成功，但运行第2条语句一定会导致崩溃。我新学的android编程，找不到是什么原因。
这个属于很严重的bug，导致FFmpegBox完全不能用。
试了很多github上的FFmpeg for Android，最后还是决定选这个FFmpegBox。您有空的时候还是修正一下吧，可能就是几行语句的问题。
谢谢！

**Comment by parcool** [comment]
@gavinliu 麻烦贴一下你的FFmpeg版本和buildScript，我这里编译出来include的里没有libavresample导致后面一系列的错误。。。
ps：你这个命令运行方式2在6.0上不能用了吧？我反正模拟器可以，真机小米6.0都没反应了。

**Comment by parcool** [comment]
另外。音频decoder一般配哪几个？我主要是用来转音乐的。

**Comment by gavinliu** [comment]
基于 ffmpeg 二进制执行文件 + rxjava + kotlin 的版本已经更新了，没有点击二次报错了。

另外具体 ffmpeg 怎么用，另外搜索相关资料。
